import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AI } from "./action";
import "./globals.css";
import Footer from "../components/footer";
import Header from "../components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen">
          {" "}
          {/* Full viewport height and flex column */}
          <link
            rel="stylesheet"
            href="../node_modules/@chatscope/chat-ui-kit-styles/dist/default/styles.min.css"
          ></link>
          <Header />
          <main className="flex-grow">
            <AI>{children}</AI> {/* page content */}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
