# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - fantasyplstats

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COSMOS_DB_ENDPOINT: ${{ secrets.COSMOS_DB_ENDPOINT }}
      COSMOS_DB_KEY: ${{ secrets.COSMOS_DB_KEY }}
      COSMOS_DB_DATABASE: ${{ secrets.COSMOS_DB_DATABASE }}



    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip .next public package.json package-lock.json

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    

    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

        # Debug Step: List the files in the deployment package
      - name: Debug: List Files in Deployment Package
        run: |
          echo "Files in the deployment package:"
          ls -al

      # Debug Step: Print Environment Variables
      - name: Debug: Print Environment Variables
        run: |
          echo "COSMOS_DB_ENDPOINT: $COSMOS_DB_ENDPOINT"
          echo "Node.js Version:"
          node -v

      - name: Install dependencies on Azure
        run: npm install --production 
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B3D6D9792685485288BF2AE4FB8597FB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_35C2D6896B3648DABE9236A84EEA8C56 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5AD7C998561D4806951BB6DD96790104 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fantasyplstats'
          slot-name: 'Production'
          package: .

      # Debug Step: Output deployment result
      - name: Debug: Deployment Result
        if: always()
        run: |
          echo "Deployment step finished with status: ${{ job.status }}"

          