name: Build and Deploy Next.js App to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      COSMOS_DB_ENDPOINT: ${{ secrets.COSMOS_DB_ENDPOINT }}
      COSMOS_DB_KEY: ${{ secrets.COSMOS_DB_KEY }}
      COSMOS_DB_DATABASE: ${{ secrets.COSMOS_DB_DATABASE }}
      PORT: 8080  # Required for Azure compatibility

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Package build artifacts
        run: zip -r release.zip .next public package.json package-lock.json node_modules

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fantasyplstats'
          slot-name: 'Production'
          package: release.zip
